const products = [
  {
    id: 1,
    englishName: 'BurnAwayCake',
    chineseName: '藍莓花卉蛋糕',
    price: 480,
    imagePath: '/images/Cake/FlowerCake/FlowerCake_7.png',
  },
  {
    id: 2,
    englishName: 'FlowerCake',
    chineseName: '紫羅蘭花卉蛋糕',
    price: 650,
    imagePath: '/images/Cake/FlowerCake/FlowerCake_3.png',
  },
  {
    id: 3,
    englishName: 'RotatingCake',
    chineseName: '紅玫瑰花卉蛋糕',
    price: 980,
    imagePath: '/images/Cake/FlowerCake/FlowerCake_2.png',
  },
  {
    id: 4,
    englishName: 'FondantCake',
    chineseName: '白蘭花卉蛋糕',
    price: 650,
    imagePath: '/images/Cake/FlowerCake/FlowerCake_1.png',
  },
  {
    id: 5,
    englishName: '',
    chineseName: '燃燒蛋糕',
    price: 300,
    imagePath: '/images/BurnAwayCake/BurnAwayCake_2.png',
  },
  {
    id: 6,
    englishName: '',
    chineseName: '公仔造型蛋糕',
    price: 250,
    imagePath: '/images/Cake/FondantCake/FondantCake_7.png',
  },
  {
    id: 7,
    englishName: '',
    chineseName: '散水餅',
    price: 120,
    imagePath: '/images/Cookies/Cookies_Zoomin_2.png',
  },
  {
    id: 8,
    englishName: '',
    chineseName: '鮮花蛋糕',
    price: 270,
    imagePath: '/images/CelebratingCake/Wedding/CelebratingCake_Wedding_2.png',
  },
  {
    id: 9,
    englishName: '',
    chineseName: '慶祝蛋糕',
    price: 250,
    imagePath: '/images/CelebratingCake/Birthday/CelebratingCake_3.png',
  },
  {
    id: 10,
    englishName: '',
    chineseName: '旋轉蛋糕',
    price: 250,
    imagePath: '/images/RotatingCake/RotatingCake_2.png',
  },
  {
    id: 11,
    englishName: '',
    chineseName: '藍色甜甜圈',
    price: 100,
    imagePath: '/images/DounghNut/DounghNut_1.png',
  },
  {
    id: 12,
    englishName: '',
    chineseName: '美樂蒂與庫洛米曲奇',
    price: 120,
    imagePath: '/images/Cookies/Cookies_2.png',
  },
  {
    id: 13,
    englishName: '',
    chineseName: '美樂蒂與庫洛米杯子蛋糕',
    price: 75,
    imagePath: '/images/Cupcake/Cupcake_set_4.png',
  },
  {
    id: 14,
    englishName: '',
    chineseName: '水果千層酥',
    price: 125,
    imagePath: '/images/MilleFeuille/MilleFeuille_1.png',
  },
];
export default products;
